load(":display_drivers_auto/display_driver_build_auto.bzl", "display_module_entry")

display_driver_modules = display_module_entry([
                            ":display_drivers_headers_auto",
                            "//msm-kernel:mi_irq_headers",
                            "//msm-kernel:miev_headers",
                        ])
module_entry = display_driver_modules.register

#---------- MSM-DRM MODULE -------------------------

module_entry(
      name = "msm_drm",
      config_option = "CONFIG_DRM_MSM",
      path = None,
      config_srcs = {
         "CONFIG_HDCP_QSEECOM": [
            "display_drivers_auto/hdcp/msm_hdcp.c",
            "display_drivers_auto/msm/dp/dp_hdcp2p2.c",
            "display_drivers_auto/msm/sde_hdcp_1x.c",
            "display_drivers_auto/msm/sde_hdcp_2x.c",
         ],
         "CONFIG_DRM_SDE_VM" : [
            "display_drivers_auto/msm/sde/sde_vm_common.c",
            "display_drivers_auto/msm/sde/sde_vm_primary.c",
            "display_drivers_auto/msm/sde/sde_vm_trusted.c",
            "display_drivers_auto/msm/sde/sde_vm_msgq.c",
         ],
         "CONFIG_DRM_MSM_DP" : [
            "display_drivers_auto/msm/dp/dp_altmode.c",
            "display_drivers_auto/msm/dp/dp_parser.c",
            "display_drivers_auto/msm/dp/dp_power.c",
            "display_drivers_auto/msm/dp/dp_catalog.c",
            "display_drivers_auto/msm/dp/dp_catalog_v420.c",
            "display_drivers_auto/msm/dp/dp_catalog_v200.c",
            "display_drivers_auto/msm/dp/dp_aux.c",
            "display_drivers_auto/msm/dp/dp_panel.c",
            "display_drivers_auto/msm/dp/dp_link.c",
            "display_drivers_auto/msm/dp/dp_ctrl.c",
            "display_drivers_auto/msm/dp/dp_audio.c",
            "display_drivers_auto/msm/dp/dp_debug.c",
            "display_drivers_auto/msm/dp/dp_hpd.c",
            "display_drivers_auto/msm/dp/dp_aux_bridge.c",
            "display_drivers_auto/msm/dp/dp_bridge_hpd.c",
            "display_drivers_auto/msm/dp/dp_mst_sim.c",
            "display_drivers_auto/msm/dp/dp_mst_sim_helper.c",
            "display_drivers_auto/msm/dp/dp_gpio_hpd.c",
            "display_drivers_auto/msm/dp/dp_lphw_hpd.c",
            "display_drivers_auto/msm/dp/dp_display.c",
            "display_drivers_auto/msm/dp/dp_drm.c",
            "display_drivers_auto/msm/dp/dp_pll.c",
            "display_drivers_auto/msm/dp/dp_pll_5nm.c",
            "display_drivers_auto/msm/dp/dp_pll_4nm.c",
         ],
         "CONFIG_DRM_MSM_DP_MST" : [
            "display_drivers_auto/msm/dp/dp_mst_drm.c",
         ],
         "CONFIG_DRM_MSM_DP_USBPD_LEGACY" : [
            "display_drivers_auto/msm/dp/dp_usbpd.c",
         ],
         "CONFIG_DRM_MSM_SDE" : [
            "display_drivers_auto/msm/sde/sde_crtc.c",
            "display_drivers_auto/msm/sde/sde_encoder.c",
            "display_drivers_auto/msm/sde/sde_encoder_dce.c",
            "display_drivers_auto/msm/sde/sde_encoder_phys_vid.c",
            "display_drivers_auto/msm/sde/sde_encoder_phys_cmd.c",
            "display_drivers_auto/msm/sde/sde_irq.c",
            "display_drivers_auto/msm/sde/sde_core_irq.c",
            "display_drivers_auto/msm/sde/sde_core_perf.c",
            "display_drivers_auto/msm/sde/sde_rm.c",
            "display_drivers_auto/msm/sde/sde_kms_utils.c",
            "display_drivers_auto/msm/sde/sde_kms.c",
            "display_drivers_auto/msm/sde/sde_plane.c",
            "display_drivers_auto/msm/sde/sde_connector.c",
            "display_drivers_auto/msm/sde/sde_color_processing.c",
            "display_drivers_auto/msm/sde/sde_vbif.c",
            "display_drivers_auto/msm/sde_dbg.c",
            "display_drivers_auto/msm/sde_dbg_evtlog.c",
            "display_drivers_auto/msm/sde_io_util.c",
            "display_drivers_auto/msm/sde_vm_event.c",
            "display_drivers_auto/msm/sde/sde_hw_reg_dma_v1_color_proc.c",
            "display_drivers_auto/msm/sde/sde_hw_color_proc_v4.c",
            "display_drivers_auto/msm/sde/sde_hw_ad4.c",
            "display_drivers_auto/msm/sde/sde_hw_uidle.c",
            "display_drivers_auto/msm/sde_edid_parser.c",
            "display_drivers_auto/msm/sde/sde_hw_catalog.c",
            "display_drivers_auto/msm/sde/sde_hw_cdm.c",
            "display_drivers_auto/msm/sde/sde_hw_dspp.c",
            "display_drivers_auto/msm/sde/sde_hw_intf.c",
            "display_drivers_auto/msm/sde/sde_hw_lm.c",
            "display_drivers_auto/msm/sde/sde_hw_ctl.c",
            "display_drivers_auto/msm/sde/sde_hw_util.c",
            "display_drivers_auto/msm/sde/sde_hw_sspp.c",
            "display_drivers_auto/msm/sde/sde_hw_wb.c",
            "display_drivers_auto/msm/sde/sde_hw_pingpong.c",
            "display_drivers_auto/msm/sde/sde_hw_top.c",
            "display_drivers_auto/msm/sde/sde_hw_interrupts.c",
            "display_drivers_auto/msm/sde/sde_hw_vbif.c",
            "display_drivers_auto/msm/sde/sde_formats.c",
            "display_drivers_auto/msm/sde_power_handle.c",
            "display_drivers_auto/msm/sde/sde_hw_color_processing_v1_7.c",
            "display_drivers_auto/msm/sde/sde_reg_dma.c",
            "display_drivers_auto/msm/sde/sde_hw_reg_dma_v1.c",
            "display_drivers_auto/msm/sde/sde_hw_dsc.c",
            "display_drivers_auto/msm/sde/sde_hw_dsc_1_2.c",
            "display_drivers_auto/msm/sde/sde_hw_vdc.c",
            "display_drivers_auto/msm/sde/sde_hw_ds.c",
            "display_drivers_auto/msm/sde/sde_fence.c",
            "display_drivers_auto/msm/sde/sde_hw_qdss.c",
            "display_drivers_auto/msm/sde_dsc_helper.c",
            "display_drivers_auto/msm/sde_vdc_helper.c",
            "display_drivers_auto/msm/sde/sde_hw_dnsc_blur.c",
            "display_drivers_auto/msm/sde/sde_hw_rc.c",
         ],
         "CONFIG_DRM_SDE_WB" : [
            "display_drivers_auto/msm/sde/sde_wb.c",
            "display_drivers_auto/msm/sde/sde_encoder_phys_wb.c"
         ],
         "CONFIG_DRM_SDE_RSC" : [
            "display_drivers_auto/msm/sde_rsc.c",
            "display_drivers_auto/msm/sde_rsc_hw.c",
            "display_drivers_auto/msm/sde_rsc_hw_v3.c",
         ],
         "CONFIG_DRM_MSM_DSI" : [
            "display_drivers_auto/msm/dsi/dsi_phy.c",
            "display_drivers_auto/msm/dsi/dsi_pwr.c",
            "display_drivers_auto/msm/dsi/dsi_phy_hw_v3_0.c",
            "display_drivers_auto/msm/dsi/dsi_phy_hw_v4_0.c",
            "display_drivers_auto/msm/dsi/dsi_phy_hw_v5_0.c",
            "display_drivers_auto/msm/dsi/dsi_phy_timing_calc.c",
            "display_drivers_auto/msm/dsi/dsi_phy_timing_v3_0.c",
            "display_drivers_auto/msm/dsi/dsi_phy_timing_v4_0.c",
            "display_drivers_auto/msm/dsi/dsi_pll.c",
            "display_drivers_auto/msm/dsi/dsi_pll_5nm.c",
            "display_drivers_auto/msm/dsi/dsi_pll_4nm.c",
            "display_drivers_auto/msm/dsi/dsi_ctrl_hw_cmn.c",
            "display_drivers_auto/msm/dsi/dsi_ctrl_hw_2_2.c",
            "display_drivers_auto/msm/dsi/dsi_ctrl.c",
            "display_drivers_auto/msm/dsi/dsi_catalog.c",
            "display_drivers_auto/msm/dsi/dsi_drm.c",
            "display_drivers_auto/msm/dsi/dsi_display.c",
            "display_drivers_auto/msm/dsi/dsi_panel.c",
            "display_drivers_auto/msm/dsi/dsi_clk_manager.c",
            "display_drivers_auto/msm/dsi/dsi_display_test.c",
         ],
         "CONFIG_DRM_SDE_SHD": [
            "display_drivers_auto/msm/shd_drm.c",
            "display_drivers_auto/msm/shd_hw.c",
            "display_drivers_auto/msm/phys_shd_vid.c",
         ],
         "CONFIG_DSI_PARSER" : [
            "display_drivers_auto/msm/dsi/dsi_parser.c",
         ],
         "CONFIG_THERMAL_OF" : [
            "display_drivers_auto/msm/msm_cooling_device.c",
          ],
         "CONFIG_DRM_MSM" : [
            "display_drivers_auto/msm/msm_atomic.c",
            "display_drivers_auto/msm/msm_fb.c",
            "display_drivers_auto/msm/msm_drv.c",
            "display_drivers_auto/msm/msm_gem.c",
            "display_drivers_auto/msm/msm_gem_prime.c",
            "display_drivers_auto/msm/msm_gem_vma.c",
            "display_drivers_auto/msm/msm_smmu.c",
            "display_drivers_auto/msm/msm_prop.c",
         ],
         "CONFIG_MSM_SDE_ROTATOR":{
            True: [
               "display_drivers_auto/rotator/sde_rotator_dev.c",
               "display_drivers_auto/rotator/sde_rotator_core.c",
               "display_drivers_auto/rotator/sde_rotator_base.c ",
               "display_drivers_auto/rotator/sde_rotator_formats.c",
               "display_drivers_auto/rotator/sde_rotator_util.c",
               "display_drivers_auto/rotator/sde_rotator_io_util.c",
               "display_drivers_auto/rotator/sde_rotator_smmu.c",
               "display_drivers_auto/rotator/sde_rotator_r1_wb.c",
               "display_drivers_auto/rotator/sde_rotator_r1_pipe.c ",
               "display_drivers_auto/rotator/sde_rotator_r1_ctl.c",
               "display_drivers_auto/rotator/sde_rotator_r1.c",
               "display_drivers_auto/rotator/sde_rotator_r3.c"],
            "CONFIG_SYNC_FILE":["display_drivers_auto/rotator/sde_rotator_sync.c"],
            "CONFIG_DEBUG_FS":["display_drivers_auto/rotator/sde_rotator_debug.c",
                              "display_drivers_auto/rotator/sde_rotator_r1_debug.c",
                              "display_drivers_auto/rotator/sde_rotator_r3_debug.c"],
            },
          "CONFIG_MI_DISP_AUTO":{
            True: [
               "display_drivers_auto/msm/mi_disp/maxim967xx/max96755.c",
               "display_drivers_auto/msm/mi_disp/maxim967xx/max96781.c",
               "display_drivers_auto/msm/mi_disp/maxim967xx/max96789.c",
               "display_drivers_auto/msm/mi_disp/maxim967xx/max967xx.c",
               "display_drivers_auto/msm/mi_disp/mi_ext_panel/mi_ext_panel.c",
               "display_drivers_auto/msm/mi_disp/mi_ext_panel/hud.c",
               "display_drivers_auto/msm/mi_disp/mi_ext_panel/panel_common.c",
               "display_drivers_auto/msm/mi_disp/mi_ext_panel/i2c_interface.c",
               "display_drivers_auto/msm/mi_disp/mi_ext_panel/ivi.c",
               "display_drivers_auto/msm/mi_disp/mi_ext_panel/ivi_backlight.c",
               "display_drivers_auto/msm/mi_disp/mi_ext_panel/ivi_touch.c",
               "display_drivers_auto/msm/mi_disp/mi_ext_panel/ivi_pogo.c",
               "display_drivers_auto/msm/mi_disp/mi_ext_panel/ivi_common.c",
               "display_drivers_auto/msm/mi_disp/mi_ext_panel/cluster.c",
               "display_drivers_auto/msm/mi_disp/mi_dp_mst_topology/drm_dp_mst_topology_ser.c",
               "display_drivers_auto/msm/mi_disp/mi_common/mi_disp_print.c"],
            },
      },
      deps = [
         "//vendor/qcom/opensource/mm-drivers/hw_fence:%b_msm_hw_fence",
         "//vendor/qcom/opensource/mm-drivers/sync_fence:%b_sync_fence",
         "//vendor/qcom/opensource/mm-drivers/msm_ext_display:%b_msm_ext_display",
         "//vendor/qcom/opensource/mmrm-driver:%b_mmrm_driver",
         "//vendor/qcom/opensource/securemsm-kernel:%b_hdcp_qseecom_dlkm"
      ],
)
